### ISSUE TITLE
Dialog to add issue to milestone

### ISSUE THREAD

**Issue by tsnik** [AndreySBer/ForkHub#10]
List of all issues without milestone

FR: 23-27

**Comment by tsnik** [comment]
Содержит:
* Список задач  
Варианты исполнения:
  * Только задачи без майлстоуна
  * Все задачи
  * Фильтры, как на вкладке задач
* Элемент создания новой задачи

**Comment by tsnik** [comment]
@AndreySBer

**Comment by phansier** [comment]
@tsnik запрашивал решение по вопросу выбора одной реализации из трех
К одной задаче нельзя прицепить несколько майлстонов, поэтому второй вариант уступает первому.
Про фильтры не понял.

**Comment by tsnik** [comment]
@AndreySBer 
Второй вариант возможен, чтобы быстро перенести задачу из одно майлстоуна в другой
На вкладке задач можно фильтровать задачи по майлстоуну, открытости/закрытости, исполнителю

**Comment by phansier** [comment]
Всё я понял. Если в задачах проекта нажать на "Открытые задачи", появятся фильтры.

**Comment by phansier** [comment]
@tsnik Можно спросить заказчика, только если показать ему макеты вариантов (иначе он как и я будет долго втупливать).
Отправляй задачу на анализ UX-специалисту @Motoaleks

**Comment by tsnik** [comment]
@AndreySBer Если показать заказчику варианты, то он сразу выберет последний, так как она наиболее полный, а нам его сложнее всего делать
Лучше начать обсуждение с первого или второго

**Comment by phansier** [comment]
@tsnik для этого все равно нужны макеты

**Comment by tsnik** [comment]
@AndreySBer один макет, так как выглядят первый и второй вариант одинаково абсолютно, отличия только в наполнении
И заказчику нужно выбрать не как сделать, а что сделать
Тут макеты ещё не нужны, достаточно вменяемого описания

**Comment by phansier** [comment]
@tsnik ок. но хотя бы скрин показать надо
+ ради одной фичи писать нет смысла. надо набрать пулл вопросов

**Comment by tsnik** [comment]
@AndreySBer Ну скрин откуда у нас, макет, если только
И не думаю, что обязательно нужно, главное доступно и понятно описать

Про одну фичу согласен, поэтому и запрашиваю лейбл для задач, требующих уточнение у заказчика, чтобы потом не потерять

**Comment by phansier** [comment]
Вчера обсудили с Женей и Никитой.
Пришли к решению: мы делаем возможность добавления существующих ишьюс, но не добавление.
На странице редактирования вехи.

Будет реализовано в виде диалога, как при добавлении майлстоуна к ишье, только вместо radio button - чекбоксы

**Comment by tsnik** [comment]
![milestone_addIssues_dialog.png.PNG](https://images.zenhubusercontent.com/59bc0ed2b0222d5de477e734/ca45a2da-bead-4569-833b-0ad7c01b1c49)
