### ISSUE TITLE
User Stories analysis

### ISSUE THREAD

**Issue by phansier** [AndreySBer/ForkHub#14]
Необходимо проанализировать существующее приложение и выявить места, в которых возникают US связанные с мильстонами.
Выявленные User Stories зафиксировать в виде эпиков, к которым впоследствии будут прикреплены дев таски.
В описании эпика: скрин экрана, какие элементы интерфейса добавляем, какие действия по ним совершаются.

**Comment by phansier** [comment]
Основная часть в части описания US и тасков - на Никите.
Задача Саши - помочь с нахождением ВСЕХ экранов, подлежащих переработке и затем уже таск из Icebox по примерному накидыванию макетов.

**Comment by Motoaleks** [comment]
In my focus.

**Comment by tsnik** [comment]
Анализ есть, два эпика:
* Про изменения работы с задачами (Немного внести изменения в 2 экрана)
* Про создание экранов для работы с майлстоунами (Необходимо создать 5 экрана(экраны создания и редактирования пока посчитаны отдельно) и внести изменения в один старый экран)

**Comment by phansier** [comment]
@tsnik там точно больше двух экранов

**Comment by tsnik** [comment]
@AndreySBer ок, добавил ещё us на добавление лейблов майлстоунов к ишьюс
Делаем в последнюю очередь, если вообще делаем
