### ISSUE TITLE
Create new/edit screens layouts (in paint)

### ISSUE THREAD

**Issue by phansier** [AndreySBer/ForkHub#19]
После выявления юзер сторей определить, где мы какие кнопки добавляем, как выглядят новые экраны. Условно говоря в пеинте, не надо заморачиваться по поводу качества макетов.

**Comment by Motoaleks** [comment]
Waiting for user stories to complete. As soon as possible.

**Comment by Motoaleks** [comment]
Макеты помещены в соответствующие задачи. 
Обсуждение по конкретному макету - в задаче макета.

**Comment by phansier** [comment]
@Motoaleks Исправить макет по письму Джона

**Comment by Motoaleks** [comment]
Макет поправлен согласно письму от 30.10.17

**Comment by phansier** [comment]
@Motoaleks Создать макет для добавления новых issues к milestone (диалоговое окно, как при добавлении milestone к issue).
