### ISSUE TITLE
Begin SRS (TZ)

### ISSUE THREAD

**Issue by phansier** [AndreySBer/ForkHub#21]

**Comment by arepina** [comment]
Я правильно понимаю, что SRS надо из серии как мы делали в прошлом году? Сейчас рыбу накидать, а постепенно заполнять?

**Comment by phansier** [comment]
@arepina по таймингу да, по формату - ГОСТ-19

**Comment by arepina** [comment]
@AndreySBer что за тайминг? можно использовать русские слова и понятнее выражаться

**Comment by arepina** [comment]
В ГОСТ-19 входит много разных документов(https://ipiskunov.blogspot.ru/2016/06/19.html), какие из них требуется предоставить? Только ТЗ, как указано в шапке этой задачи?

**Comment by phansier** [comment]
@arepina в рамках этой таски только ТЗ

**Comment by arepina** [comment]
@AndreySBer ok

**Comment by UEvgeniy** [comment]
Не забудьте добавить таблицу с основными, второстепенными и обособленными задачами

**Comment by phansier** [comment]
@arepina Структуру ТЗ по Беловой надо прислать или ты записала?
++ Как можно запараллелить ТЗ кроме макетов? (вопрос также к @tsnik)
От @Motoaleks ждем макеты

**Comment by arepina** [comment]
@UEvgeniy Насколько я услышала она говорила о данной таблице как о доп задании, которое выполняется отдельно от ТЗ. Она про нее уже после того как рассказ про ТЗ закончила говорила

**Comment by arepina** [comment]
@AndreySBer Можешь прислать и свои записи, я могла что-то упустить

**Comment by phansier** [comment]
@arepina если в тз не надо - тогда отдельный таск под это дело сделаю
Записи пришлю, когда домой приеду

**Comment by phansier** [comment]
@arepina теперь надо добавить переписку с йоханом в основания для разработки

**Comment by phansier** [comment]
@arepina Нужно обновить макеты в ТЗ
+ Добавить в глоссарии к milestone "веха"

**Comment by arepina** [comment]
@AndreySBer есть какая-то папка со всеми макетами? или надо их по задачам разыскивать?

**Comment by phansier** [comment]
Есть. Нужно смотреть конфу)
Рядом с тз

**Comment by arepina** [comment]
@AndreySBer я вообще-то читаю, что там пишут. у меня минуту назад папки не было, вместо нее была папка протоколы, видимо опять диск глючит. все нашла, спасибо

**Comment by phansier** [comment]
Ладно, сорян. У меня тоже гдиск лагает
