### ISSUE TITLE
Date & time input realization details and mockups

### ISSUE THREAD

**Issue by phansier** [AndreySBer/ForkHub#28]
На основе сравнительного анализа выбрать один способ ввода даты для milestone'а, описать его в виде функциональных требований, добавить скриншот (мокап для последующей реализации).

**Comment by phansier** [comment]
![milestone_edit&create_page#10_v2.png](https://images.zenhubusercontent.com/59bbf3eab0222d5de477e353/8befc405-8f6c-4334-a9d7-52c3715a0f41)
По нажатию на Choose date открывается стандартный календарь Android

**Comment by Motoaleks** [comment]
![image](https://user-images.githubusercontent.com/11456215/32415481-6c13f278-c24b-11e7-9df3-794595de47bf.png)
