### ISSUE TITLE
View closed issues on milestone view page

### ISSUE THREAD

**Issue by Motoaleks** [AndreySBer/ForkHub#32]
Если android API позволяет, то при скролле вниз, описание "уплывает" вверх, оставляя на экране только вкладки ACTIVE/CLOSED.
![image](https://user-images.githubusercontent.com/11456215/32406898-53f3117a-c191-11e7-9075-f7e8e8413185.png)

**Comment by phansier** [comment]
Функциональность будет реализована как на макете в issue #8
