### ISSUE TITLE
Project architecture

### ISSUE THREAD

**Issue by phansier** [AndreySBer/ForkHub#36]
Архитектура проекта. Должны быть не только представлены все необходимые диаграммы, но и расписаны блоки. Это делается для того, чтобы при возникновении необходимости расширения или другой модификации проекта, разработчик точно знал как и куда дописывать новые/изменять части проекта.

**Comment by Motoaleks** [comment]
Результаты в папке архитектура и в корневом каталоге:
- Forkhub.html (draw.io): файл с диаграммами
- Инструкция разработчику: разъяснения по архитектуре

@AndreySBer @tsnik @arepina Совет - перед началом выполнения тасков - прочитать файл "инструкция разработчику" на диске (а именно задания, заметки и комментарии к вашему таску), посмотреть классы аналоги и их реализацию, какие методы использованы, от кого унаследованы.

![forkhub 4](https://user-images.githubusercontent.com/11456215/32693057-3cd357d0-c735-11e7-8ce9-8091e2777b93.png)

**Comment by UEvgeniy** [comment]
Также для Беловой UC Model и State Machine Diagram:
![forkhub](https://user-images.githubusercontent.com/14293557/32693126-5bc434b0-c736-11e7-86a4-42e231099e95.jpg)
![forkhub 1](https://user-images.githubusercontent.com/14293557/32693124-5ba66d22-c736-11e7-9183-d7b353d70b86.jpg)

**Comment by UEvgeniy** [comment]
Небольшая визуальная модификация class diagram:
<img width="485" alt="forkhub 1" src="https://user-images.githubusercontent.com/14293557/32693527-94422e12-c73d-11e7-9a58-0fe292f5ef98.png">

**Comment by phansier** [comment]
@Motoaleks  @UEvgeniy вы описали архитектуру только относительно части, связанной с milestone'ами?
Обсуждали же, что нужен бриф по всему приложению

**Comment by UEvgeniy** [comment]
@AndreySBer описать архитектуру всего приложения - это полно бесполезной работы, есть бриф описание пакетов, в которые мы будем добавлять классы:
###### api - взаимодействие с API (Milestone в пакете model не используется) 
###### core - логика приложения, нас интересует больше всего пакет issue
###### ui - интерфейс, нас интересует больше всего пакеты issue и repo

а также детальное взаимодействие классов, с которыми нам работать (на диаграммах выше).
