### ISSUE TITLE
Tasks actualisation

### ISSUE THREAD

**Issue by phansier** [AndreySBer/ForkHub#37]
Актуализировать таски на доске
Пометить отдельным лейблом те, которые НЕ берем в план

**Comment by tsnik** [comment]
@AndreySBer а зачем лейбл, мы их просто складываем в беклог, если берем и можем уже делать
И в айсбокс, если берем, но делать ещё не можем

**Comment by phansier** [comment]
@tsnik Не все таски с доски можно взять для показа Беловой в плане

**Comment by tsnik** [comment]
@AndreySBer 
Почему не все? Скорее даже не все таски, что должны быть в плане, есть на доске
Все что, в айсбоксе и в бэклоге берём
Структуру эпиков сохраняем

**Comment by phansier** [comment]
@tsnik я не стал включать low priority
