### ISSUE TITLE
View activities architecture and dependencies analysis

### ISSUE THREAD

**Issue by Motoaleks** [AndreySBer/ForkHub#40]
Анализ зависимостей activity и fragment элементов.

**Comment by phansier** [comment]
@Motoaleks  Про что здесь? Какие артефакты на выходе таска?

**Comment by Motoaleks** [comment]
Это и инструкция.
![image](https://user-images.githubusercontent.com/11456215/32698511-599b21bc-c7b8-11e7-92c9-d15d59e2cd82.png)
