### ISSUE TITLE
Data/api architecture and dependencies analysis

### ISSUE THREAD

**Issue by Motoaleks** [AndreySBer/ForkHub#41]
Анализ зависимостей данных в реализуемых компонентах программы

**Comment by phansier** [comment]
@UEvgeniy Про что здесь? Какие артефакты на выходе таска?

**Comment by UEvgeniy** [comment]
https://drive.google.com/drive/u/0/folders/1Y9rzXxhFMrLQYWnUxgz0aFLpTHm6Aiq7

Картинки на выходе, инструкция нам. По вопросам API, UC и StateMachine ко мне, по UI к @Motoaleks
