### ISSUE TITLE
Edit milestone doesn't change "due to date"

### ISSUE THREAD

**Issue by UEvgeniy** [AndreySBer/ForkHub#64]
1. Open milestone list
2. Select milestone with due to date
3. Edit
4. Clear date
5. Save
6. Nothing happened. Date is still exists

**Comment by Motoaleks** [comment]
Проблема при установки due_on в null. Retrrofit?
Ожидаемое поведение: обнуление даты, если подано due_on = null.
Текущее поведение: возвращение предыдущей даты, без ошибки, в методе onSuccess
@tsnik

**Comment by Motoaleks** [comment]
Воспроизвести проблему:

new EditMilestoneTask(this, repositoryId.getOwner(), repositoryId.getName(), milestone) {

``` java
                        @Override
                        protected void onSuccess(Milestone editedMilestone)
                                throws Exception {
                            super.onSuccess(editedMilestone);

                            Intent intent = new Intent();
                            intent.putExtra(EXTRA_MILESTONE, editedMilestone);
                            setResult(RESULT_OK, intent);
                            finish();
                        }
                    }.edit();
```

с milestone.due_on = null.
Строчка 289 EditMilestoneActivity.

**Comment by Motoaleks** [comment]
Остальное поправил.

**Comment by phansier** [comment]
Fixed but now new milestone is not saving. Will be in new bug
