### ISSUE TITLE
List view of all repository milestones

### ISSUE THREAD

**Issue by tsnik** [AndreySBer/ForkHub#7]
FR: 2-8, 22

**Comment by tsnik** [comment]
Добавить вкладку "майлстоуны"
Аналогично задачам, плюс будет добавлять новый майлстоун
Поиск и фильтрация не нужна
![Screenshot_20171016-190855.png](https://images.zenhubusercontent.com/59bc0ed2b0222d5de477e734/3733506e-97df-4cb7-b976-562995c3bb3f)

**Comment by tsnik** [comment]
Нужен все-таки фильтрация по открытым/закрытым майлстоунам
Нужен макет, как это сделать красиво без доп активити @Motoaleks

**Comment by Motoaleks** [comment]
123

**Comment by Motoaleks** [comment]
Макет.
![image](https://user-images.githubusercontent.com/11456215/31855153-8ee9f9a4-b6ad-11e7-8e1f-fc023f9fc005.png)

**Comment by phansier** [comment]
@Motoaleks  Откуда ты скрин брал? Или ты с нуля перерисовывал?
Календарь в майлстоне кликабельный или какую он нагрузку несет?

**Comment by Motoaleks** [comment]
Скрин proto.io. С нуля.
Календарь в майлстоне не кликабельный, показывает дату окончания майлстоуна (как в гитхабе - скриншот ниже)
![image](https://user-images.githubusercontent.com/11456215/32398648-aa40bb76-c101-11e7-9eaa-a36bfe637ccd.png)

**Comment by Motoaleks** [comment]
Макет поправленный по письму от 30.10.17
![image](https://user-images.githubusercontent.com/11456215/32399081-67db7e8a-c104-11e7-945e-c7c072a9af5c.png)
![image](https://user-images.githubusercontent.com/11456215/32399462-2696a460-c107-11e7-8b29-9a2859bd8247.png)
