### ISSUE TITLE
Check and pass ui tests

### ISSUE THREAD

**Issue by phansier** [AndreySBer/ForkHub#72]
All tests besides one are passed.
Need to check, whether this test worked before.
If worked - fix

**Comment by arepina** [comment]
Этот тест падает в последней версии мастера репозитория johan'а и у нас тоже. Я пофиксила еще один тест, про который писал Никита, что падал у нас. 
![tsgqrvbu1au](https://user-images.githubusercontent.com/16975514/35615477-4d5599d2-0683-11e8-8570-5a8d6129f760.jpg)
