### ISSUE TITLE
Milestone is not displaying in issue opened from milestone view

### ISSUE THREAD

**Issue by phansier** [AndreySBer/ForkHub#73]
**Repro steps:**
Open milestone list.
Open milestone with issues.
Open issue.
Go into edit mode.
**Expected:**
In milestone field current milestone is showing.
**Actual:**
Milestone field is empty

UPDATE:
**Another Repro steps:**
Open repository issues list.
Open issue.

**Comment by tsnik** [comment]
Added another repro steps
