### ISSUE TITLE
Milestone view page

### ISSUE THREAD

**Issue by tsnik** [AndreySBer/ForkHub#8]
Like issue page + list of issues with active links + button to add issue to milestone

FR: 9-17, 27

**Comment by tsnik** [comment]
На всякий случай перевожу на русский, что должно быть на странице:  
* Имя майлстоуна
* Дата
* Элемент добавления новой задачи
* Список задач в майлстоуне
* Меню, аналогичное меню в задаче  
![Screenshot_20171016-192518.png](https://images.zenhubusercontent.com/59bc0ed2b0222d5de477e734/b08ce1e4-7527-40a5-86d2-f8862d152f52)

**Comment by tsnik** [comment]
Ещё описание, конечно же

**Comment by tsnik** [comment]
Ещё статус выполнения майлстоуна должен быть
![image.png](https://images.zenhubusercontent.com/59bc0ed2b0222d5de477e734/8c934181-69ee-4760-8171-3a803ce76b7e)

**Comment by Motoaleks** [comment]
Макет.
- плюс - добавление новой задачи
- Список скроллится и описание "уплывает" вверх
- тэг кол-ва дней по возможности
- меню аналогично задачам
![image](https://user-images.githubusercontent.com/11456215/31855333-b87099fa-b6b1-11e7-93f5-706a91f26694.png)

**Comment by phansier** [comment]
Добавил чутка реалистичности в макет
![1.png](https://images.zenhubusercontent.com/59bbf3eab0222d5de477e353/48a14ecf-6005-41bf-bd3c-1f363af15751)

**Comment by Motoaleks** [comment]
Добавочный макет. Требование "Закрыть milestone"
![image](https://user-images.githubusercontent.com/11456215/32406937-e7d8bd5e-c191-11e7-87f1-da6fd1b93a34.png)

**Comment by phansier** [comment]
![milestone_view_page#8.png](https://images.zenhubusercontent.com/59bbf3eab0222d5de477e353/e812d4a3-9350-40a7-96e8-86057b9e171b)

**Comment by Motoaleks** [comment]
Ключевой функционал (описание, меню, список) 
к **20.12 23:59**

**Comment by Motoaleks** [comment]
Запаздываю.
