### ISSUE TITLE
Manual testing

### ISSUE THREAD

**Issue by phansier** [AndreySBer/ForkHub#84]

**Comment by UEvgeniy** [comment]
Tested next cases:

1. View MS (ms list + detailed view):
	1.1 - only opened issues 		- ok
	1.2 - only closed issues 		- ok
	1.3 - with both 			- ok
	1.4 - without both			- ok
	1.5 - with empty date			- ok
	1.6 - with empty description		- ok
2. Create MS:
	2.1 - without title			- ok (no toast "Enter title")
	2.2 - without description		- fail (issue #87)
	2.3 - without date			- fail (issue #87)
3. Edit MS:
	3.1 - change/remove title		- fail (issue #88)
	3.2 - add/change/remove description	- ok
	3.3 - add/change/remove date		- fail (issue #89)
4. Filter MS:
	4.1 - open/closed			- ok
	4.2 - asigneed to			- ok
	4.3 - by MS (?)				- fail (issue #90)
	4.1 - tags				- ok
5. Bind MS to issue:
	5.1 - opened issue			- ok
	5.2 - closed issue			- ok
6. Bind issue to MS				- ok
7. Localization:
	7.1 - Russian				- question (Цель или Цели)
	7.2 - English				- ok (no space between "due by" and date in create page)
