### ISSUE TITLE
Milestone edit/create page

### ISSUE THREAD

**Issue by tsnik** [AndreySBer/ForkHub#9]
Edit page with ability to edit:
Title
Description
Due date

FR: 18-22

**Comment by tsnik** [comment]
Еще проще, чем просмотр:  
* Название
* Описание
* Дата (не извращаемся, юзаем стандартные элементы дроида)

**Comment by Motoaleks** [comment]
Макет. Ракета=самолёт в оригинальном приложении
![image](https://user-images.githubusercontent.com/11456215/31855200-78240de4-b6ae-11e7-9b73-773a7f358efc.png)

**Comment by phansier** [comment]
@Motoaleks что происходит по самолёту-ракете? Сохраняется?
Отдельное решение нужно по формату выбора даты

**Comment by tsnik** [comment]
@AndreySBer Да, сохраняется

**Comment by Motoaleks** [comment]
Переделан согласно Функциональным требованиям
![image](https://user-images.githubusercontent.com/11456215/32415314-1a431c00-c249-11e7-8825-f88ac3ede512.png)
