### ISSUE TITLE
Filter by Milestones

### ISSUE THREAD

**Issue by UEvgeniy** [AndreySBer/ForkHub#90]
1. open ms view
2. select ms with opened issues
3. Press filter button
4. Filter by anoter milestone
5. Activity partly refreshed:
![image](https://user-images.githubusercontent.com/14293557/35560874-bcd76b9c-05bf-11e8-8c62-91086c740735.png)
May be that filter option is needless?

**Comment by phansier** [comment]
Сам себя дублируешь 
Дупликат #70
